spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb